### ISSUE TITLE
[FEAT] QA 1 Junseo

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#108]
## 📝 todo

- [x] 로그인 화면 제목 업데이트
- [x] 로그인 화면 설명 업데이트
- [ ] 아이콘 깨짐 업데이트
- [x] 구글 로그인 클릭 시 기본 토스트 메시지 띄우기 : "구글 로그인은 추후 업데이트 예정입니다"
- [x] API request 2번씩 날라가는 버그 수정
- [x] 회원탈퇴 기능 구현
- [x] 약관 밎 정책 링크 연결
- [x] 탈퇴 사유 설문 폼
- [x] 로그아웃 dialog 창 만들기
- [x] MyPageInformationActivity 닉네임 -> 유저명
- [ ] 앱 아이콘 변경
- [x] 실천 행동 -> 실천 방법
- [x] 생성, 수정 뷰 낫투두 클릭 시 앱 터짐
- [x] 오늘, 내일, 모레, 외 n일 처리
- [x] 수정 뷰 수정 성공 시 setResult
