### ISSUE TITLE
[FEAT] 커스텀 스낵바 적용

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#124]
## 💡 Issue
생성한 커스텀 스낵바를 적용합니다.

## 📝 todo
- [x] 추천 뷰 커스텀 스낵바 적용
- [x] 생성 뷰 커스텀 스낵바 적용
- [x] 수정 뷰 커스텀 스낵바 적용
- [x] 수정 뷰에 세트 낫투두 date list 가져오기
