### ISSUE TITLE
[FEAT] 생성 뷰 터치영역 개선 및 이슈 수정

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#131]
## 💡 Issue

생성 뷰 터치영역 개선 및 이슈 수정
## 📝 todo

- [ ] 터치영역 변경
- [ ] 실천방법 행간 수정
- [ ] 체크표시, title 항상 위에 있도록 수정
- [ ] 필요 없어요 or 직접 입력할게요 터치 이벤트 수정
- [ ] 동영상 끝나고 버튼 띄우기
