### ISSUE TITLE
[FEAT] onboarding view

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#28]
## 💡 Issue
온보딩 뷰 제작

## 📝 todo
- [ ] 명언 연속 등장 (살짝 아래서 위로 올라오듯이, 투명도가 점점 불투명해짐)
- [ ] 로고 등장 (살짝 아래서 위로 올라오듯이, 투명도가 점점 불투명해짐)
- [ ] 로고가 올라가며 소개 글 등장. 
- [ ] 소개글을 대충 다 읽었을 때쯤 튜토리얼 화면으로 연결 -> 고민 화면
- [ ] 고민 클릭 시 1초정도 정지 후 개선 상황들이 나오는 화면으로 전환
- [ ] 1개 이상 클릭 시, 사용법이 궁금해요 버튼 활성화, 다중선택 가능, 버튼 클릭 시 사용 방법 탭으로 전환
