### ISSUE TITLE
[Feat] home server

### ISSUE THREAD

**Issue by cbj0010** [DO-NOTTO-DO/AOS-NOTTODO#35]
## 💡 Issue
home뷰 서버연결 할것임

## 📝 todo

- [x] daily 조회
- [x] todo 성공시 patch
- [x] 주간 낫투두 조회 get
        홈 바텀시트
- [x] 낫투두 삭제 delete
- [x] 낫투두 상세 조회 get
