### ISSUE TITLE
[Feat] Home 캘린더 서버 및 주간캘린더 

### ISSUE THREAD

**Issue by cbj0010** [DO-NOTTO-DO/AOS-NOTTODO#55]
## 💡 Issue
홈화면에서 낫투두 다른 날짜도 할래요 캘린더랑 주간 캘린더 관련해서 서버 연동 및 기능구현
캘린더 관련한거

## 📝 todo

- [ ] 낫투두 다른 날짜에도 추가 post
- [ ] 바텀네비 탭 클릭시 재생성 막기
- [x] 주간 캘린더에서 값 가져와서 동그라미 이미지 보여주기
- [x] 주간에서 날짜 클릭시 그 날짜 가져오기(더미 바꾸기)
