### ISSUE TITLE
[FEAT] 내 정보 뷰 리팩토링

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#70]
## 💡 Issue
내 정보 뷰 리팩토링을 진행합니다.

## 📝 todo
- [x] 이전 MyPageFragment의 내용 찾아서 합치기
- [x] 터치 영역 조절
- [x] 로그아웃 기능 구현
