### ISSUE TITLE
[FEAT]생성 뷰 기초 제작

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#8]
## 💡 Issue
생성 뷰 기초 제작

## 📝 todo
- [x] 생성 뷰 기본 구현
- [x] 양방향 데이터 바인딩 구현
- [x] 리사이클러 뷰로 낫투두 추천
- [x] Flexbox레이아웃으로 추천 행동 구현
- [x] 토글 기능 구현
