### ISSUE TITLE
[FEAT] 정보 뷰 추가 기능 구현

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/AOS-NOTTODO#89]
## 💡 Issue
정보 뷰의 남은 기능들을 구현합니다.

## 📝 todo
- [ ] 회원 탈퇴 API
- [ ] 정보 뷰 Switch
- [ ] 사용자 이름, 이메일 받아오기
- [ ] 수정 뷰도 날짜까지 날릴 수 있도록 수정할게요
